Update convert.yml

diff --git a/.github/workflows/convert.yml b/.github/workflows/convert.yml
--- a/.github/workflows/convert.yml
+++ b/.github/workflows/convert.yml
@@ -24,13 +24,13 @@ jobs:
           mv sing-box-1.10.3-linux-amd64/sing-box ./sing-box
           chmod +x sing-box
 
-      # Step 3: 遍历并转换所有 JSON 文件
+      # Step 3: 转化修改的 JSON 文件
       - name: Convert JSON Files to SRS
         run: |
-          for json_file in *.json; do
+          for json_file in $(git diff --name-only HEAD^ HEAD | grep '\.json$'); do
             echo "Converting $json_file..."
             srs_file="${json_file%.json}.srs"
-            ./sing-box run -c "$json_file" || exit 1
+            ./sing-box run -c "$json_file" || { echo "Failed to process $json_file"; exit 1; }
             mv rules.srs "$srs_file"
           done
 
